name: preset_app
description: Preset App for Flutter
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  before_after: ^2.1.0
  image_picker: ^0.6.7+21
  share: ^0.6.5+4
  screenshot: ^0.2.0
  google_mobile_ads: ^0.11.0+4
  provider: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/categories/
    - assets/data/
    - assets/lang/
